# Python Fundamentals

In [2]:
# Libraries
import os
from pathlib import Path
import sys
import numpy as np
# import dataframe library
import pandas as pd

# Change working directory to the project root
if Path.cwd().name == 'notebooks':
    os.chdir(Path.cwd().parent)
PROJECT_ROOT = os.getcwd()
print("PROJECT ROOT:", PROJECT_ROOT)

# load environment functions
from src.config import load_env, get_key
from src.utils import summary_df

PROJECT ROOT: c:\Users\samla\OneDrive\Documentos 1\Documentos\ELAB\Maestría\NYU\Bootcamps\Documents(BootCamp)(FRE5040)(Fall 2026)\bootcamp-esteban-lopez-araiza-bravo
Imports OK

In [3]:
# Import data from CSV file
data_file_path = Path("data/raw/starter_data.csv")

# read with pandas
df = pd.read_csv(PROJECT_ROOT / data_file_path)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  10 non-null     object
 1   value     10 non-null     int64
 2   date      10 non-null     object
dtypes: int64(1), object(2)
memory usage: 368.0+ bytes

In [4]:
df.head()

  category  value        date
0        A     10  2025-08-01
1        B     15  2025-08-02
2        A     12  2025-08-03
3        B     18  2025-08-04
4        C     25  2025-08-05

We can also use the summary_df function to get a summary of the dataframe:
summary_df(df)

In [5]:
# Change date column to datetime
df['date'] = pd.to_datetime(df['date'], format="%Y-%m-%d")
summary_df(df)

Column: category
  Data Type: object
Column: value
  Data Type: int64
Column: date
  Data Type: datetime64[ns]
Data type 'category': object
  Group by 'category':
category
A    4
B    3
C    3
dtype: int64
Data type 'value': int64
Data type 'date': datetime64[ns]

In [6]:
# Groupby category and then mean of value column
grouped_df = df.groupby('category').mean()
grouped_df

              value                date
category
A         11.500000 2025-08-05 06:00:00
B         15.666667 2025-08-04 16:00:00
C         27.666667 2025-08-06 16:00:00

In [8]:
# save grouped data to CSV
grouped_df.to_csv(PROJECT_ROOT / Path("data/processed/summary.csv"))

In [10]:
# Re read the grouped data to verify
grouped_df = pd.read_csv(PROJECT_ROOT / Path("data/processed/summary.csv"))
grouped_df

  category      value                 date
0        A  11.500000  2025-08-05 06:00:00
1        B  15.666667  2025-08-04 16:00:00
2        C  27.666667  2025-08-06 16:00:00